moncom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("supervision.urls")),
]

supervision/api/urls.py
from django.db.models import base
from rest_framework.routers import DefaultRouter

from .views import PredefTextViewSet


router = DefaultRouter()
router.register('predef_texts', PredefTextViewSet, basename='predef_texts')

supervision/urls.py
from django.urls import path, include, reverse_lazy, reverse
from django.contrib.auth import views as auth_views

from .views import session_views
from .views import core_views
from .views import account_views

# from .api.urls import router


urlpatterns = [
    path("", core_views.HomeView.as_view(), name="home"),
    path("dashboard", core_views.DashboardView.as_view(), name="dashboard"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", account_views.SignupView.as_view(), name="register"),
    path(
        "accounts/activate/<uidb64>/<token>",
        account_views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "accounts/log_in",
        auth_views.LoginView.as_view(
            template_name="accounts/log_in.html",
            redirect_authenticated_user=True,
            redirect_field_name="home",
        ),
        name="log_in",
    ),
    path(
        "accounts/log_out",
        auth_views.LogoutView.as_view(next_page="home"),
        name="log_out",
    ),
    path(
        "accounts/password_change",
        account_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url=reverse_lazy("user"),
        ),
        name="password_change",
    ),
    # path('accounts/password_change/done',
    #      auth_views.PasswordChangeDoneView.as_view(next_page='user'),
    #      name='password_change_done'),
    path(
        "accounts/password_reset",
        account_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/reset/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("user", account_views.UserView.as_view(), name="user"),
    path("sessions", session_views.SessionsListView.as_view(), name="sessions"),
    path(
        "controller",
        session_views.QuickstartSessionView.as_view(),
        name="create_session",
    ),
    path(
        "controller/<session_id>",
        session_views.ControllerView.as_view(),
        name="controller",
    ),
    path(
        "receiver/<session_id>", session_views.ReceiverView.as_view(), name="receiver"
    ),
    path("templates", session_views.TemplatesListView.as_view(), name="templates"),
    path(
        "templates/<uuid:pk>",
        session_views.EditTemplateView.as_view(),
        name="edit_template",
    ),
]

supervision/models.py
import re
import uuid
import logging

from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.db.models.fields import related
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

# from versatileimagefield.fields import VersatileImageField, PPOIField

from .tools import make_short_uuid


LOGGER = logging.getLogger("moncom")
User._meta.get_field("email")._unique = True


class Profile(models.Model):
    class Subscription(models.TextChoices):
        BASIC = "BSC", _("Basic")
        SUPPORTER = "SPT", _("Supporter")
        PROFESSIONAL = "PRO", _("Professional")

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    ts_and_cs_agreed = models.BooleanField(default=False)
    ts_and_cs = models.CharField(max_length=10000, blank=True)
    reset_password = models.BooleanField(default=False)
    subscription = models.CharField(
        max_length=3, choices=Subscription.choices, default=Subscription.BASIC
    )


class Participant(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    joined_at = models.DateTimeField(auto_now_add=True)
    last_seen = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=80, default="")
    ip_address = models.CharField(max_length=15, default="")
    is_permitted = models.BooleanField(default=False)
    messages_received = models.IntegerField(default=0)
    session = models.ForeignKey("Session", on_delete=models.CASCADE, null=True)

    def set_permission(self, permitted):
        self.is_permitted = permitted
        self.save()
        LOGGER.debug(f"Set participant {self.id} permission to {permitted}")

    def increment(self):
        self.messages_received += 1
        self.save()

    def set_name(self, name):
        self.name = name
        self.save()
        LOGGER.debug(f"Set participant {self.id} name to {name}")

    class Meta:
        ordering = ["joined_at"]


class Session(models.Model):
    class Status(models.TextChoices):
        OPEN_DOOR = "OPN", _("Open door")
        CLOSED_DOOR = "CLS", _("Closed door")
        PASSWORD_PROTECTED = "PWD", _("Password protected")

    id = models.CharField(
        primary_key=True,
        max_length=12,
        default=make_short_uuid,
        unique=True,
        editable=False,
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    template = models.ForeignKey(
        "Template", on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(max_length=64, default="Quickstart", null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    status = models.CharField(
        max_length=3, choices=Status.choices, default=Status.OPEN_DOOR
    )
    last_used = models.DateTimeField(auto_now=True, null=True)
    current_message = models.OneToOneField(
        "Message",
        on_delete=models.CASCADE,
        null=True,
        related_name="currently_in_session",
    )
    is_running = models.BooleanField(default=False)
    latest_run_start = models.DateTimeField(auto_now=True, null=True, blank=True)
    password = models.CharField(max_length=256, null=True, blank=True)

    class Meta:
        ordering = ["-last_used"]

    def set_password(self, password):
        self.password = password
        self.save()
        LOGGER.debug(f"Set session {self.id} password to {password}")

    def check_password(self, password):
        return password == self.password


class Message(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(blank=True, default=now)
    from_template = models.BooleanField(default=False)

    class Meta:
        ordering = ["-timestamp"]

    def get_type(self):
        if hasattr(self, "text"):
            return "text"
        elif hasattr(self, "image"):
            return "image"

    def get_child(self):
        if self.get_type() == "text":
            return self.text
        elif self.get_type() == "image":
            return self.image
        else:
            return ""


class Template(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, default="New template")
    last_used = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return f"{self.name} ({len(self.text_set.all())} texts, {len(self.image_set.all())} images)"


class PredefText(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    template = models.ForeignKey(
        Template, on_delete=models.CASCADE, null=True, related_name="text_set"
    )
    content = models.CharField(max_length=1000, editable=False)
    duration = models.DecimalField(decimal_places=1, max_digits=8, default=0)

    class Meta:
        verbose_name_plural = "Predefined texts"

    def strip_html(self):
        """Removes html code from a string so that word counts are accurate.

        e.g. if self.content = "<p style="text-align: center;">Example message</p>",
            the function returns "Example message"

        Returns:
            str: `self.content` with html tags removed.
        """
        clean_regex = re.compile("<.*?>")
        return re.sub(clean_regex, "", self.content)


class PredefImage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    template = models.ForeignKey(
        Template, on_delete=models.CASCADE, null=True, related_name="image_set"
    )
    content = models.ImageField(upload_to="session_images")
    duration = models.DecimalField(decimal_places=1, max_digits=8, default=0)

    class Meta:
        verbose_name_plural = "Predefined images"


class TextMessage(models.Model):
    message = models.OneToOneField(
        Message, on_delete=models.CASCADE, related_name="text"
    )
    content = models.CharField(max_length=1000, editable=False)
    duration = models.DecimalField(decimal_places=1, max_digits=8, default=0)

    class Meta:
        verbose_name_plural = "Text messages"

    def strip_html(self):
        """Removes html code from a string so that word counts are accurate.

        e.g. if self.content = "<p style="text-align: center;">Example message</p>",
            the function returns "Example message"

        Returns:
            str: `self.content` with html tags removed.
        """
        clean_regex = re.compile("<.*?>")
        return re.sub(clean_regex, "", self.content)


class ImageMessage(models.Model):
    message = models.OneToOneField(
        Message, on_delete=models.CASCADE, related_name="image"
    )
    content = models.ForeignKey(PredefImage, on_delete=models.CASCADE)
    duration = models.DecimalField(decimal_places=1, max_digits=8, default=0)

    class Meta:
        verbose_name_plural = "Image messages"


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

supervision/api/views.py
# from rest_framework.mixins import (
#     CreateModelMixin, ListModelMixin, RetrieveModelMixin, UpdateModelMixin
# )
from re import template
from rest_framework.viewsets import ModelViewSet

from ..models import PredefText, PredefImage, Template
from .serialisers import PredefTextSerialiser, PredefImageSerialiser


class PredefTextViewSet(ModelViewSet):
    serializer_class = PredefTextSerialiser
    # queryset = PredefText.objects.all()

    def get_queryset(self):
        set_id = self.request.query_params.get('set_id')

        try:
            template_set = Template.objects.get(id=set_id)
            print(template_set)
        except Template.DoesNotExist:
            return PredefText.objects.none()

        print(PredefText.objects.filter(set=template_set))
        return PredefText.objects.filter(set=template_set)


    #   def get(self, request, format=None):
    #       content =

    # def list(self, request):
    #     print(request.POST)

# PredefImage

supervision/views/account_views.py
from datetime import datetime
import requests
import logging
import urllib
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views import View
from django.utils.encoding import force_text
from django.contrib.auth import login
from django.contrib.auth.forms import PasswordResetForm, PasswordChangeForm
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import views as auth_views
from django.conf import settings

from .. import models, forms, emails, tokens
from ..messages import get_message


@method_decorator(login_required, name="dispatch")
class UserView(TemplateView):
    template_name = "supervision/user.html"

    # def get(self, request):
    #     if request.user.is_authenticated:
    #         return redirect(reverse("dashboard"))


class SignupView(FormView):
    template_name = "accounts/sign_up.html"
    form_class = forms.SignUpForm
    success_url = "/"

    def get(self, request):
        if request.user.is_authenticated:
            message = get_message("USER_ALREADY_REGISTERED", {})
            messages.add_message(self.request, messages.INFO, message)
            return redirect(reverse("dashboard"))
        else:
            return super().get(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recaptcha_site_key"] = settings.RECAPTCHA_PUBLIC_KEY
        return context

    def form_valid(self, form):
        recaptcha_response = self.request.POST.get("g-recaptcha-response")
        url = "https://www.google.com/recaptcha/api/siteverify"
        data = {
            "secret": settings.RECAPTCHA_PRIVATE_KEY,
            "response": recaptcha_response,
        }
        r = requests.post(url, data=data)
        result = r.json()

        if result["success"]:
            logging.info("Creating new user")
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            site = get_current_site(self.request)

            email = emails.user_registered(user, site)

            try:
                email.send()
                logging.info("Email sent")
                message = get_message("EMAIL_VERIFY_SENT", {"email": user.email})
                messages.add_message(self.request, messages.SUCCESS, message)
            except Exception as error:
                logging.error(error)

                message = get_message(
                    "ERROR",
                    {"timestamp": datetime.now().isoformat(), "error_message": error},
                )
                messages.add_message(self.request, messages.WARNING, message)
        else:
            messages.add_message(
                self.request,
                messages.WARNING,
                "reCAPTCHA was invalid. Please try again.",
            )

        return super().form_valid(form)


class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist) as error:
            message = get_message(
                "ERROR",
                {"timestamp": datetime.now().isoformat(), "error_message": error},
            )
            messages.add_message(request, messages.WARNING, message)
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.profile.email_confirmed = True
            user.save()
            login(request, user)

            message = get_message("EMAIL_VERIFIED", {"username": user.username})
            messages.add_message(request, messages.INFO, message)
            return redirect("dashboard")
        else:
            message = get_message("ACCOUNT_ACTIVATION_LINK_INVALID", {})
            messages.add_message(request, messages.WARNING, message)
            return redirect("home")


class PasswordResetView(FormView):
    template_name = "accounts/password_reset.html"
    form_class = PasswordResetForm

    def form_valid(self, form):
        email_address = form["email"].value()
        logging.info(f"Password reset link requested for email {email_address}")

        try:
            user = User.objects.get(email=email_address)
            logging.info(f"User {user.username} found")
            site = get_current_site(self.request)
            email = emails.reset_password(user, site)
            email.send()
            logging.info("Email sent")
        except User.DoesNotExist:
            logging.info(f"No user found with that email address")
        except Exception as error:
            logging.error(error)

        message = get_message("PASSWORD_RESET", {"email": email_address})
        messages.add_message(self.request, messages.INFO, message)

        return redirect(reverse("home"))


class PasswordChangeView(auth_views.PasswordChangeView):
    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO, "Your password was changed")

        return super().form_valid(form)

supervision/templates/supervision/_base.html
{% load static %}
<!doctype html>

<head>
    <title>
        MonCom – {% block title %}{% endblock %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'supervision/fonts/fontawesome-free-5.15.1-web/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/base.css' %}?{% now ' u'='' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/colours.css' %}?{% now ' u'='' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/menu.css' %}?{% now ' u'='' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/forms.css' %}?{% now ' u'='' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/list.css' %}?{% now ' u'='' %}">
    {% block stylesheets %}{% endblock %}

    {% if recaptcha_site_key %}
        <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
    {% endif %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>

    {% block header_scripts %}{% endblock %}
</head>

<body>
    <div id="popup-container" style="display: none;">
        {% block popups %}{% endblock %}
    </div>

    <div id="umbrella-flex">
        {% include "./menu.html" %}

        {% if show_controller_view %}
            <div class="content-container" id="controller-container">
                {% block controller %}
                {% endblock %}
            </div>
        {% elif show_template_view %}
            <div class="content-container" id="template-container">
                {% block template %}
                {% endblock %}
            </div>
        {% else %}
            <div class="content-container" id="grid-container">
                <div id="grid-body">
                    <header class="grid-box-header">{% block header %}{% endblock %}</header>
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        {% endif %}
    </div>

    <div id="message-container">
        {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="message-popup {{ message.tags }}"{% endif %}>
                <div class="message-icon"></div>
                <div class="message-text">
                    <!-- {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %} -->
                    {{ message }}
                </div>
                <div class="message-close">
                    <button onclick="$(this).parents()[2].remove();">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    </div>

    <script type="text/javascript" src="{% static 'supervision/scripts/base.js' %}?{% now ' u'='' %}"></script>

    {% if recaptcha_site_key %}
    <script>
        grecaptcha.ready(function() {
            grecaptcha.execute("{{ recaptcha_site_key }}", {action: "/contact/"}).then(function(token) {
                document.getElementById("g-recaptcha-response").value = token;
            });
        });
    </script>
    {% endif %}
    {% block scripts %}{% endblock %}

</body>

supervision/templates/supervision/dashboard.html
{% extends "supervision/_base.html" %}

{% block title %}Dashboard{% endblock %}

{% block header %}Dashboard{% endblock %}

{% block body %}
    <content class="narrow-content">
        <p>Use the menu to start a new session or create a new template.</p>
    </content>
{% endblock %}

supervision/templates/supervision/menu.html
<div id="menu">

    {% include "./menu_button.html" with path=" " title="Home page" fa_class="fas fa-home" label="Home"%}

    {% if user.is_authenticated %}

        {% include "./menu_button.html" with path="controller" title="Quickstart session" fa_class="fas fa-bolt" label="Quickstart"%}

        {% include "./menu_button.html" with path="sessions" title="View all sessions" fa_class="fas fa-chalkboard-teacher" label="Sessions"%}

        {% include "./menu_button.html" with path="templates" title="Create and edit templates" fa_class="fas fa-th-list" label="Templates"%}

        <!-- {% include "./menu_button.html" with path="sequences" title="Create and edit sequences" fa_class="fas fa-list-ol" label="Sequences"%} -->

    {% endif %}

    <div id="menu-filler"></div>

    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            {% include "./menu_button.html" with path="admin" title="Django Admin" fa_class="fas fa-user-shield" label="Admin" %}
        {% endif %}

        {% include "./menu_button.html" with path="user" title="View user page" fa_class="fas fa-user" label=user.username %}

        {% include "./menu_button.html" with path="accounts/log_out" title="Log out of this session" fa_class="fas fa-sign-out-alt" label="Log out"%}

    {% else %}
        {% include "./menu_button.html" with path="accounts/register" title="Create an account" fa_class="fas fa-user-plus" label="Sign up"%}

        {% include "./menu_button.html" with path="accounts/log_in" title="Log in" fa_class="fas fa-sign-in-alt" label="Log in"%}
    {% endif %}


    {% include "./menu_button.html" with path="help" title="View help pages" fa_class="fas fa-question" label="Help" extra_class="bottommost" %}
</div>

supervision/templates/supervision/menu_button.html
<div class="menu-section {{ extra_class }}">
    <a href="/{{ path }}" title="{{ title }}" class="menu-tab menu-button">
        <div class="icon-container">
            <i class="{{ fa_class }}"></i>
        </div>
        <div class="label-container">
            {{ label }}
        </div>
    </a>
</div>

supervision/templates/supervision/sessions.html
{% extends "supervision/_base.html" %}

{% load static %}

{% block title %}Sessions{% endblock %}

{% block header %}Sessions{% endblock %}

{% block body %}
<content>
    <div>
        <table id="list-table">
            <thead>
            <tr>
                <th>Status</th>
                <th class="wider-column">Name</th>
                <th class="wider-column">ID</th>
                <th class="wider-column">Latest Run</th>
                <th class="widest-column">Last Message</th>
            </tr>
            </thead>
            <tbody>
                {% for session in sessions %}
                    <tr class="list-table-row" onclick="openController('{{ session.id }}')">
                        <td class="cell-with-icon">
                            {% if session.is_running %}
                                <i class="fa-large fas fa-lightbulb" title="Session is live"></i>
                            {% else %}
                                <i class="fa-large far fa-lightbulb" title="Session is inactive"></i>
                            {% endif %}

                            {% if session.status == "OPN" %}
                                <i class="fa-large fas fa-door-open" title="Open door policy"></i>
                            {% elif session.status == "CLS" %}
                                <i class="fa-large fas fa-door-closed" title="Participants require permission"></i>
                            {% else %}
                                <i class="fa-large fas fa-key" title="Password protected"></i>
                            {% endif %}
                            <!-- {% if session.is_locked and not session.is_running %}
                                <i class="fa-large far fa-lightbulb" title="Inactive"></i>
                            {% endif %} -->
                        </td>
                        <td>{{ session.name }}</td>
                        <td>{{ session.id }}</td>
                        <td>{{ session.latest_run_start }}</td>
                        <td class="text-column"
                            title="{{ session.message_set.first.get_child.content }}">
                            {{ session.message_set.first.get_child.strip_html }}
                        </td>
                    </tr>
                {% empty %}
                    <!-- <tr class="list-table-row">
                        <td class="cell-with-icon">Empty!</td>
                        <td>Open new session below...</td>
                        <td></td>
                        <td></td>
                    </tr> -->
                {% endfor %}
            </tbody>
        </table>
        <div class="linewidth-centered-input-container">
            <button class="button-with-icon" onclick="showPopup('session-form');" type="button">
                <i class="fas fa-plus"></i>
                Open new session
            </button>
        </div>

    </div>
</content>
{% endblock %}

{% block popups %}
    <div class="popup" id="session-form">
        <header>
            Open new session
        </header>
        <form method="POST">
            {% csrf_token %}
            {{ session_form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

supervision/templates/supervision/templates.html
{% extends "supervision/_base.html" %}

{% load static %}

{% block title %}Templates{% endblock %}

{% block header %}Templates{% endblock %}

{% block body %}
<content>
    <div>
        <table id="list-table">
            <thead>
            <tr>
                <th class="wider-column">Name</th>
                <th class="wider-column">Sessions</th>
                <th class="wider-column">Text</th>
                <th class="wider-column">Images</th>
                <th class="wider-column">Last Used</th>
            </tr>
            </thead>
            <tbody>
                {% for template in templates %}
                    <tr class="list-table-row" onclick="openTemplate('{{ template.id }}')">
                        <td>{{ template.name }}</td>
                        <td>
                            {% if template.session_set.all %}
                                {{ template.session_set.all|length }} ({{ template.session_set.first.name }}, ...)
                            {% else %}
                                None
                            {% endif %}
                            </td>
                        <td>
                            {% if template.text_set.all %}
                                {{ template.text_set.all|length }} ({{ template.text_set.first.strip_html }}, ...)
                            {% else %}
                                None
                            {% endif %}
                        </td>
                        <td>
                            {% if template.image_set.all %}
                                {{ template.image_set.all|length }} ({{ template.image_set.first.content }}, ...)
                            {% else %}
                                None
                            {% endif %}
                        </td>
                        <td>{{ template.last_used }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="linewidth-centered-input-container">
            <button class="button-with-icon" onclick="showPopup('template-form');" type="button">
                <i class="fas fa-plus"></i>
                Create new template set
            </button>
        </div>

    </div>
</content>
{% endblock %}

{% block popups %}
    <div class="popup" id="template-form">
        <header>
            Create new template set
        </header>
        <form method="POST">
            {% csrf_token %}
            {{ template_form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

supervision/templates/supervision/user.html
{% extends "supervision/_base.html" %}
{% load static %}


{% block title %}User – {{ user.username }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'supervision/style/user.css' %}?{% now ' u'='' %}">
{% endblock %}

{% block header %}
    Settings
{% endblock %}

{% block body %}
<div id="user-container-main">
    <div class="user-grid-section">
        <div class="user-grid-label">
            Membership status
        </div>
        <div class="user-grid-item">
            {{ user.profile.get_subscription_display }}
        </div>
    </div>

    <div class="horizontal-spacer">

    </div>

    <div class="user-grid-section">
        <div class="user-grid-label">
            Username
        </div>
        <div class="user-grid-item">
            {{ user.username }}
        </div>
    </div>

    <div class="user-grid-section">
        <div class="user-grid-label">
            Email
        </div>
        <div class="user-grid-item">
            {{ user.email }}
        </div>
    </div>

    <div class="user-grid-section">
        <div class="user-grid-label">
            Password
        </div>
        <div class="user-grid-item">
            <a href="/accounts/password_change">Change</a>
        </div>
    </div>

    <div class="user-grid-section">
        <div class="user-grid-label">
            Deactivate account
        </div>
        <div class="user-grid-item">

        </div>
    </div>
</div>
{% endblock %}